title: "Jilin Tian"
description: "Personal Website"
baseurl: "" # keep this empty for user/organization pages
url: "https://jilintian.github.io" # your GitHub Pages URL
show_downloads: true
google_analytics: G-TKBDCHKL2Z
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
