title: "Jilin Tian"
description: "Personal Website"
baseurl: "" # keep this empty for user/organization pages
url: "https://jilintian.github.io" # your GitHub Pages URL
show_downloads: true
google_analytics: G-TKBDCHKL2Z
theme: jekyll-theme-minimal 
